export const WS_EVENTS = {
  CORE: {
    DISCONNECT: 'disconnect',
    KICKED: 'kicked',
  },
  ROOM: {
    JOIN_ROOM: 'join-room',
    PEER_JOINED: 'peer-joined',
    OFFER: 'offer',
    ANSWER: 'answer',
    ICE_CANDIDATE: 'ice-candidate',
    PEER_DISCONNECTED: 'peer-disconnected',
  },
  STATION: {
    REGISTER: 'station-register',
    INVITE: 'station-invite',
    REQUEST_STATUS: 'station-request-status',
    CONNECTED: 'station-connected',
    DISCONNECTED: 'station-disconnected',
    CMD_REQUEST_STREAM: 'station-cmd-request-stream',
    CMD_START_STREAM: 'station-cmd-start-stream',
    CMD_STREAM_RESPONSE: 'station-cmd-stream-response',
    STREAM_READY: 'station-stream-ready',
    INCOMING_CALL: 'station-incoming-call',
    STATUS_UPDATE: 'station-status-update',
    BATCH_STATUS_UPDATE: 'batch-station-status-update',
    CMD_JOIN_ROOM: 'station-cmd-join-room',
    CALL_CENTER: 'station-call-center',
  },
} as const

export const WS_ERRORS = {
  UNAUTHORIZED: '登录已过期，请重新登录',
  FORBIDDEN: '没有权限执行此操作',
  INVALID_ARGUMENT: '参数错误，请检查输入',
  NOT_FOUND: '资源不存在',
  CONFLICT: '资源冲突，请稍后重试',
  FAILED_PRECONDITION: '操作条件未满足',
  RESOURCE_EXHAUSTED: '资源已满或请求过于频繁',
  INTERNAL: '服务内部错误，请稍后重试',
  UNAVAILABLE: '服务暂不可用，请稍后重试',
  ROOM_NOT_FOUND: '房间不存在',
  ROOM_FULL: '房间已满',
  ROOM_CLOSED: '房间已关闭',
  ROOM_ALREADY_EXISTS: '房间已存在',
  ROOM_ALREADY_JOINED: '已在房间中',
  ROOM_INVALID_STATE: '房间状态异常',
  SIGNAL_OFFER_INVALID: '信令 Offer 无效',
  SIGNAL_ANSWER_INVALID: '信令 Answer 无效',
  SIGNAL_ICE_INVALID: '信令 ICE 候选无效',
  SIGNAL_PEER_NOT_FOUND: '对端不存在或已离线',
  STATION_NOT_FOUND: '站点不存在',
  STATION_OFFLINE: '站点离线',
  STATION_ALREADY_REGISTERED: '站点已注册',
  STATION_NOT_REGISTERED: '站点未注册',
  STATION_UNREACHABLE: '站点不可达',
} as const
